runtime: nodejs14
service: wedding-planner-authentication
instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 2

service_account:  wedding-datastore-computer@wedding-planner-project-caalim.iam.gserviceaccount.com 